### ISSUE TITLE
좌클릭시 메뉴발생

### ISSUE THREAD

**Issue by yongseokleecom** [nhn/tui.context-menu#14]
예제에서 우클릭시 컨텍스트 메뉴 실행되는데
혹시 좌 클릭시에도 메뉴실행이 가능하나요?

**Comment by jung-han** [comment]
@yongseokleecom 현재는 다른 방법을 제공하고 있지 않습니다.

**Comment by yongseokleecom** [comment]
@jung-han 
답변 감사합니다.
