### ISSUE TITLE
Uncaught TypeError: dom.on is not a function 에러 뜨네요..

### ISSUE THREAD

**Issue by kungfumong** [nhn/tui.context-menu#8]
감사합니다.

**Comment by seonim-ryu** [comment]
@kungfumong 
[`tui-dom`](https://github.com/nhnent/tui.dom)이 디펜던시로 추가되지 않은 것 같습니다.
그리고 추후 문의 시 이슈 템플릿에 맞추어 작성 부탁드립니다.
감사합니다.
